name: ci

on: push

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  ubt2004_llvm10_146:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Sys Info
        run: |
          lscpu
          free -h

      - name: Dep install
        run: |
          sudo apt-get update -y
          sudo apt-get install -y clang-10 lld-10
          rustup install 1.46.0

      - name: Compile Rust
        run: |
          CC=clang-10 RUSTFLAGS="-Clinker-plugin-lto -Clinker=clang-10 -Clink-arg=-fuse-ld=lld-10" cargo +1.46.0 build --release

      - name: objdump
        run: |
          objdump -d ./target/release/xlanglto | grep "<multiply>:" -A3 -P3

  debiansid_llvm14_164:
    runs-on: ubuntu-20.04
    container: debian:sid

    steps:
      - uses: actions/checkout@v2

      - name: Sys Info
        run: |
          lscpu

      - name: Dep install
        run: |
          apt-get update -y
          apt-get install -y clang-14 lld-14 curl
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          PATH="$HOME/.cargo/bin:$PATH"
          rustup install 1.64.0

      - name: Compile Rust
        run: |
          PATH="$HOME/.cargo/bin:$PATH"
          CC=clang-14 RUSTFLAGS="-Clinker-plugin-lto -Clinker=clang-14 -Clink-arg=-fuse-ld=lld-14" cargo +1.64.0 build --release

      - name: objdump
        run: |
          objdump -d ./target/release/xlanglto | grep "<multiply>:" -A3 -P3

  debiansid_llvm14_latest:
    runs-on: ubuntu-20.04
    container: debian:sid

    steps:
      - uses: actions/checkout@v2

      - name: Sys Info
        run: |
          lscpu

      - name: Dep install
        run: |
          apt-get update -y 
          apt-get install -y clang-14 lld-14 curl
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          PATH="$HOME/.cargo/bin:$PATH"

      - name: Compile Rust
        run: |
          PATH="$HOME/.cargo/bin:$PATH"
          CC=clang-14 RUSTFLAGS="-Clinker-plugin-lto -Clinker=clang-14 -Clink-arg=-fuse-ld=lld-14" cargo build --release

      - name: objdump
        run: |
          objdump -d ./target/release/xlanglto | grep "<multiply>:" -A3 -P3
