name: ci

on: push

env:
  DEBIAN_FRONTEND: noninteractive
  PATH: "$HOME/.cargo/bin:$PATH"

jobs:
  ubt2004_llvm9_142:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Sys Info
        run: |
          sudo apt update -y
          sudo apt install -y clang-9 lld-9
          rustup install 1.42.0
          # -------------------
          cat /etc/*release
          rustc --version 
          clang --version

      - name: Compile Rust
        run: |
          CC=clang-9 RUSTFLAGS="-Clinker-plugin-lto -Clinker=clang-9 -Clink-arg=-fuse-ld=lld-9" cargo +1.42.0 build --release

      - name: objdump
        run: |
          objdump -d ./target/release/xlanglto | grep "<multiply>:" -A3

  ubt2004_llvm10_146:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Sys Info
        run: |
          sudo apt update -y
          sudo apt install -y clang-10 lld-10
          rustup install 1.46.0

      - name: Compile Rust
        run: |
          CC=clang-10 RUSTFLAGS="-Clinker-plugin-lto -Clinker=clang-10 -Clink-arg=-fuse-ld=lld-10" cargo +1.46.0 build --release

      - name: objdump
        run: |
          objdump -d ./target/release/xlanglto | grep "<multiply>:" -A3

  ubt2110_llvm13_latest:
    runs-on: ubuntu-20.04
    container: ubuntu:21.10

    steps:
      - uses: actions/checkout@v2

      - name: Sys Info
        run: |
          apt update -y
          apt install -y clang-13 lld-13 curl
          curl https://sh.rustup.rs -sSf | sh -s -- -y

      - name: Compile Rust
        run: |
          CC=clang-13 RUSTFLAGS="-Clinker-plugin-lto -Clinker=clang-13 -Clink-arg=-fuse-ld=lld-13" cargo build --release

      - name: objdump
        run: |
          objdump -d ./target/release/xlanglto | grep "<multiply>:" -A3
