name: ci

on: push

jobs:
  ubuntu2004:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Sys Info
        run: |
          cat /etc/*release
          sudo apt update -y
          sudo apt install -y clang-9 lld-9
          rustup install 1.42.0

      - name: Compile Rust
        run: |
          CC=clang-9 RUSTFLAGS="-Clinker-plugin-lto -Clinker=clang-9 -Clink-arg=-fuse-ld=lld-9" cargo +1.42.0 build --release

      - name: objdump
        run: |
          objdump -d ./target/release/xlanglto | grep "<multiply>:" -A3

  container_ubuntu2110:
    runs-on: ubuntu-20.04
    container: ubuntu:21.10

    steps:
      - uses: actions/checkout@v2

      - name: Sys Info
        run: |
          cat /etc/*release
          apt update -y
          apt install -y clang-9 lld-9
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          rustup install 1.42.0

      - name: Compile Rust
        run: |
          CC=clang-9 RUSTFLAGS="-Clinker-plugin-lto -Clinker=clang-9 -Clink-arg=-fuse-ld=lld-9" cargo +1.42.0 build --release

      - name: objdump
        run: |
          objdump -d ./target/release/xlanglto | grep "<multiply>:" -A3

