name: ci

on: push

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  ubt2004_llvm10_146:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Sys Info
        run: |
          sudo apt update -y
          sudo apt install -y clang-10 lld-10
          rustup install 1.46.0

      - name: Compile Rust
        run: |
          CC=clang-10 RUSTFLAGS="-Clinker-plugin-lto -Clinker=clang-10 -Clink-arg=-fuse-ld=lld-10" cargo +1.46.0 build --release

      - name: objdump
        run: |
          objdump -d ./target/release/xlanglto | grep "<multiply>:" -A3 -P3

  ubt2110_llvm13_stable:
    runs-on: ubuntu-20.04
    container: ubuntu:21.10

    steps:
      - uses: actions/checkout@v2

      - name: Sys Info
        run: |
          apt update -y
          apt install -y clang-13 lld-13 curl
          curl https://sh.rustup.rs -sSf | sh -s -- -y

      - name: Compile Rust
        run: |
          PATH="$HOME/.cargo/bin:$PATH"
          CC=clang-13 RUSTFLAGS="-Clinker-plugin-lto -Clinker=clang-13 -Clink-arg=-fuse-ld=lld-13" cargo build --release

      - name: objdump
        run: |
          objdump -d ./target/release/xlanglto | grep "<multiply>:" -A3 -P3

  debiansid_llvm13_nightly:
    runs-on: ubuntu-20.04
    container: debian:sid

    steps:
      - uses: actions/checkout@v2

      - name: Sys Info
        run: |
          apt update -y
          apt upgrade -y
          apt install -y clang-13 lld-13 curl
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          PATH="$HOME/.cargo/bin:$PATH"
          rustup install nightly

      - name: Compile Rust
        run: |
          PATH="$HOME/.cargo/bin:$PATH"
          CC=clang-13 RUSTFLAGS="-Clinker-plugin-lto -Clinker=clang-13 -Clink-arg=-fuse-ld=lld-13" cargo +nightly build --release

      - name: objdump
        run: |
          objdump -d ./target/release/xlanglto | grep "<multiply>:" -A3 -P3
