name: ci

on: push

jobs:
  ubuntu2004:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Sys Info
        run: |
          sudo apt update -y
          sudo apt install -y clang-9 lld-9
          rustup install 1.42.0
          # -------------------
          cat /etc/*release
          rustc --version 
          clang --version
          ldd --version

      - name: Compile Rust
        run: |
          CC=clang-9 RUSTFLAGS="-Clinker-plugin-lto -Clinker=clang-9 -Clink-arg=-fuse-ld=lld-9" cargo +1.42.0 build --release

      - name: objdump
        run: |
          objdump -d ./target/release/xlanglto | grep "<multiply>:" -A3

  ubuntu2004_latest:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Sys Info
        run: |
          sudo apt update -y
          sudo apt install -y clang-10 lld-10
          rustup install 1.46.0
          # -------------------
          cat /etc/*release
          rustc --version 
          clang --version
          ldd --version

      - name: Compile Rust
        run: |
          CC=clang-10 RUSTFLAGS="-Clinker-plugin-lto -Clinker=clang-10 -Clink-arg=-fuse-ld=lld-10" cargo +1.46.0 build --release

      - name: objdump
        run: |
          objdump -d ./target/release/xlanglto | grep "<multiply>:" -A3

  container_ubuntu2110:
    runs-on: ubuntu-20.04
    container: ubuntu:21.10

    steps:
      - uses: actions/checkout@v2

      - name: Sys Info
        run: |
          whoami
          pwd
          ls
          apt update -y
          apt install -y clang-9 lld-9 curl
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source $HOME/.cargo/env
          rustup install 1.42.0
          # -------------------
          cat /etc/*release
          rustc --version 
          clang --version
          ldd --version

      - name: Compile Rust
        run: |
          CC=clang-9 RUSTFLAGS="-Clinker-plugin-lto -Clinker=clang-9 -Clink-arg=-fuse-ld=lld-9" cargo +1.42.0 build --release

      - name: objdump
        run: |
          objdump -d ./target/release/xlanglto | grep "<multiply>:" -A3

  container_ubuntu2110_llvm13:
    runs-on: ubuntu-20.04
    container: ubuntu:21.10

    steps:
      - uses: actions/checkout@v2

      - name: Sys Info
        run: |
          whoami
          pwd
          ls
          apt update -y
          apt install -y clang-13 lld-13 curl
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          echo "------- echo home cargo env"
          echo $HOME/.cargo/env
          echo "------- cat home cargo env"
          cat $HOME/.cargo/env
          echo "------- ls home cargo "
          ls $HOME/.cargo/
          source $HOME/.cargo/env
          # -------------------
          cat /etc/*release
          rustc --version 
          clang --version
          ldd --version

      - name: Compile Rust
        run: |
          CC=clang-13 RUSTFLAGS="-Clinker-plugin-lto -Clinker=clang-13 -Clink-arg=-fuse-ld=lld-13" cargo build --release

      - name: objdump
        run: |
          objdump -d ./target/release/xlanglto | grep "<multiply>:" -A3
